[package]
name = "smfh"
version = "1.0.0"
edition = "2021"


[dependencies]
blake3 = {version = "1.6.1", features = ["mmap"] }
clap = { version = "4.5.31", features = ["derive"] }
color-eyre = "0.6.3"
log = "0.4.26"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
simplelog = "0.12.2"

[profile.release]
strip = true
opt-level = 3
lto = "fat"
codegen-units = 1 
